a_dynamic_method: per_token
abits: 4
act_symmetric: false
alpha: 0.5
attn_implementation: eager
auto_lr_scale: true
batch_size: 1
cache_dir: ./cache
calib_dataset: wikitext2
circular_aug: false
config: configs/llama2-7b-w4a4-plus/config.yaml
deactive_amp: false
debug: false
disable_zero_point: false
epochs: 20
eval_ppl: false
export_model_mode: fp16
export_model_path: null
fill_window_size: 4
fp16_act: false
gqa_scales: copy
grad_clip: null
group_size: null
inference_batch_size: 2
last_round_inp_num: 1
layer_windows_scheduler: null
layers_assigned_gpu: 0,1,2,3
let: true
limit: -1
littlt_bs_round: null
lm_eval_batch_size: '64'
load_rotate_model_path: ./rotate_models/llama2-7B-rotate-plus.pth
lora_iter_num_list: null
lora_layer_list: null
lora_lr: 0.0001
lora_quant: true
lora_r_list: null
lora_rank: 4
loss_function: mse
loss_type: mean
low_cpu_memory: false
low_memory: true
lwc: true
lwc_lr: 0.01
max_train_steps: null
model: model_zoo/Llama-2-7b-hf
multigpu: false
net: Llama-2-7b
nsamples: 128
num_layer: 4
online_had: true
output_dir: configs/llama2-7b-w4a4-plus
parallelize: false
quant_gate: false
quant_layer_list: null
quant_mode: slider
quant_mode_layer_list: null
quant_rate: 0.5
quant_rate_list: null
quant_step: 2
quant_warp: false
resume: null
resume_layers_num: null
scale_lr: 0.001
seed: 2
seqlen: 2048
sliding_layer: 2
start_round: 0
symmetric: false
tasks: ''
teach_model: null
test_datasets: wikitext2,c4
test_mode: false
train_last_round: false
train_resume: null
update_gate: false
use_base_loss: last
use_bfloat16: true
use_ddp: false
use_down_scale: false
use_fp_inp_loss: false
use_lora: true
use_lr_scheduler: true
use_quant_tar_loss: false
w_dynamic_method: per_channel
warmup_ratio: 0.0
wbits: 4
wd: 0.0
weight_merge: false
wo_lwc: false
